### ISSUE TITLE
should I subset the scRNA data or the ST data?

### ISSUE THREAD

**Issue by Danyking** [navinlabcode/CellTrek#10]
Hello,

I have a scRNA-seq data with more than 20K cells with 19 celltypes, and ST data with 23k spots. Now I want to detect all the celltypes distribution on the ST with celltrek function. But this process takes too much computing memory, about 200G, so I want to subset the data and analyze separately. I was wondering should I subset the scRNA data and map to the ST data, then merge the results together, or subset the ST data?

Best regards,
thanks!

**Comment by WandeRum** [comment]
Hi @Danyking . I think you can probably downsample your data and try CellTrek. But for ST-Visium, the total number is 5,000 on one sample, I am curious what kinda ST data you have?
