### ISSUE TITLE
tissue_possitions_lists and images outputs for sample DCIS1 and DCIS2

### ISSUE THREAD

**Issue by ruqianl** [navinlabcode/CellTrek#11]
Hi @WandeRum,

Congratulations on the great tool!

Thanks for generating and sharing the datasets.
I'm interested in the two human tumour samples analyzed in the cellTrek paper,  and wondering if you could share the image outputs and the tissue_possitions_lists. I'm trying to reproduce the spatial plots.

Thanks,
Ruqian

**Comment by WandeRum** [comment]
Hi, there are some problems with sharing spatial data on GEO. Please check the dropbox link here for more information on the two DCIS data (https://www.dropbox.com/sh/gxaa54962tdi28z/AAAHIBpz7Esv4J_lmSEoXjKHa?dl=0).

**Comment by ruqianl** [comment]
Thanks a lot for the dropbox link. I got the files downloaded successfully!
