### ISSUE TITLE
Utilizing CellChat after CellTrek

### ISSUE THREAD

**Issue by kguion1** [navinlabcode/CellTrek#17]
Hi, Thank you for such a great tool! I noticed in the paper you described utilizing CellChat after CellTrek to incorporate the spatial information into CellChat. Is there code to go along with this example?

**Comment by WandeRum** [comment]
Hi, Thank you for your interest. Basically, we used the cell-cell colocalization matrix to re-weight the cell-cell interaction matrix from CellChat. We'll update our tutorials with more data and examples soon.
