### ISSUE TITLE
Publicly available Single cell data with ST data

### ISSUE THREAD

**Issue by AteeqMKhaliq** [navinlabcode/CellTrek#27]
As a researcher using spatial transcriptomics data but without my own single-cell data, I find CellTrek to be a wonderful tool for deconstructing microenvironments. I am interested in incorporating publicly available single-cell RNA sequencing (scRNA-seq) data into my CellTrek analysis to gain additional insights. Can you please elaborate on the recommended approaches for integrating publicly available scRNA-seq data with CellTrek when single-cell data is not available? Thank you!
Best,
Ateeq Khaliq

**Comment by williamhsy** [comment]
For normal tissues, it should be fine if you don't have matched scRNA-seq data, which we demonstrated in the paper (mouse data analysis). 
However, for tumor samples, it is a different story. It would be ideal only using matched tumor cells. TME cells could come from different samples. Also see [https://github.com/navinlabcode/CellTrek/issues/28](url)
