### ISSUE TITLE
Simualtion dataset

### ISSUE THREAD

**Issue by hiraksarkar** [navinlabcode/CellTrek#6]
Hi Team,

Congratulation on the amazing work. It seems simulating different conditions is a critical portion of the paper. However, I could not find function or method to repeat those simulation. Is it possible to share the code for simulating the datasets from the paper. I am especially referring to Supp Fig 4

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/9473877/160842987-6ef7e13e-3ffe-4ab4-baf5-94a8ea3bbf5f.png">

**Comment by WandeRum** [comment]
Hi. Thank you. The simulation data and script were not included in the SI yet. But we are happy to share them if you want to test. Please contact me through my Email address.

**Comment by 13198910213** [comment]
Dear Professor:
Hello! First of all, congratulations for doing such a good job. We are very interested in your training using simulated data, but did not find a relevant method to create simulated data. Could you provide the source code and data for constructing the simulated data in your thesis, thank you very much! My e-mail address is: lixuhua@hainmc.edu.cn
