### ISSUE TITLE
Dimension reduce warning in function celltrek

### ISSUE THREAD

**Issue by parkjooyoung99** [navinlabcode/CellTrek#7]
Hello,
I have a question about dimension in 'celltrek' function.

I am running celltrek in remote server (school server) and using same nPC as in tutorial (30),
but it keeps giving me a warning message of 'please reduce dimesion if possible' and eventually kills itself. 

My sc seurat object is kind of large (50GB with 155312 cells, 33538 features)., will this be the reason?
Also, I want to know if this program is heavier than seurat and cloupe, since I experienced no problem using the same data.

Thank you!

**Comment by parkjooyoung99** [comment]
**! Internal error in `dict_hash_with()`: Dictionary is full.**

this error just bumped up and i guess this might happened because of my data size. 
If there are any idea that might be helpful for me, please let me know.

Thank you :)

**Comment by WandeRum** [comment]
Hi, I guess that's because of the data size. You can probably subset the cells randomly or by different cell types to maybe <50k cells and run the CellTrek again.
