### ISSUE TITLE
Minimum feature overlap between scRNAseq and spatial method?

### ISSUE THREAD

**Issue by annamath** [navinlabcode/CellTrek#8]
Hello! 

I was wondering whether CellTrek could also be used in combination with other spatial approaches, for example multiplexed immunofluorescence (instead of RNA measure protein level and in a lower throughput). Have you tried? What would you recommend as the minimum number of features overlap between the 2 methods (i.e. scRNAseq and spatial)? 

Thanks!

**Comment by WandeRum** [comment]
Hi, this is a great question. We only tried on whole-transcriptome data, but not on smaller panels. Thus, I cannot answer it very definitely. But, I guess if there is a way to co-embed these two data sets into a shared space, the CellTrek should work then.
