### ISSUE TITLE
Disorder coordiantes for 10x visium data.

### ISSUE THREAD

**Issue by zhou-ran** [navinlabcode/CellTrek#9]
Hi all,

I perform CellTrek on my unpublised 10x visium data with default parameters, but the predicted coordinate for each single cell couldn't match to the HE picture, here is the shiny plot.

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/15224084/163666682-bcf6ff42-0b16-4760-9a8e-fc44458f138a.png">

Best,
Ran

**Comment by WandeRum** [comment]
Hi Ran. It looks like a repelling problem. What are your repel_r and repel_iter parameters? You can probably set them to a smaller number like 5, 10, respectively. U can also check DimPlot(obj, reduction='celltrek_raw').

**Comment by zhou-ran** [comment]
Hi, 
Thanks for your advice, problem was solved perfectly by choosing smaller repel value.
Ran

**Comment by PaulaNietoG** [comment]
Hello, I'm having the same issue when using `celltrek_vis`. However, I am not able to correctly implement the changes in the `repel_x` and `repel_iter`, as I see no changes on the plot. 
Could you provide an example of how to update these two parameters?
Thanks
